### ISSUE TITLE
problem importing gslrandom after the installation

### ISSUE THREAD

**Issue by pakdaman** [slinderman/gslrandom#6]
Hi Scott,
Thank you very much for sharing your gslrandom, and pgmult codes. I recently installed both the packages successfully on my mac without error. However, when I try to import the gslrandom it raises the following error:

    from gslrandom.gslrandom import *

ImportError: dlopen(/Users/mahdi/anaconda2/lib/python2.7/site-packages/gslrandom/gslrandom.so, 2): Symbol not found: ___emutls_get_address

  Referenced from: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib

  Expected in: /usr/local/lib/libgcc_s.1.dylib

 in /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib

I am wondering if you have any suggestion how I would be able to address the problem.
Thanks,
MP

**Comment by slinderman** [comment]
Hi MP,
The installation procedure for `gslrandom` is not well documented.  On OSX, you need GSL installed and you need to compile with GNU `gcc` and `g++`.  Since we use OpenMP under the hood, you need to install `gcc` without multilib support.  I'm working from memory right now, but I believe this is achieved by 

```
brew install gcc --without-multilib
```
Then to compile `gslrandom` you would do
```
export CC=/usr/local/bin/gcc-x.x
export CXX=/usr/local/bin/g++-x.x
python setup.py build_ext --inplace
```
where `x.x` denotes the correct version number. 

What procedure did you use to install gslrandom?  Can you try the above and see if it works?

**Comment by pakdaman** [comment]
Hi Scott,
Thank you very much for your response. I just followed the step by step instructions that you mentioned. However, I could not install the package successfully, unfortunately. I am wondering if you have any advice? 

Thanks,
MP

Here are the steps that I take:

$ gcc --version
gcc (Homebrew GCC 7.1.0 --without-multilib) 7.1.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ --version
g++ (Homebrew GCC 7.1.0 --without-multilib) 7.1.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ export CXX=/usr/local/Cellar/gcc/7.1.0/bin/g++-7 
$ export CC=/usr/local/Cellar/gcc/7.1.0/bin/gcc-7  


$ python setup.py build_ext --inplace
Compiling gslrandom/gslrandom.pyx because it changed.
[1/1] Cythonizing gslrandom/gslrandom.pyx
/Users/mahdi/Research/Harvard/conda_env/asd_conda/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build_ext
building 'gslrandom.gslrandom' extension
creating build
creating build/temp.macosx-10.7-x86_64-2.7
creating build/temp.macosx-10.7-x86_64-2.7/gslrandom
/usr/local/Cellar/gcc/7.1.0/bin/gcc-7 -fno-strict-aliasing -I/Users/mahdi/Research/Harvard/conda_env/asd_conda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -Igslrandom/ -I/Users/mahdi/Research/Harvard/conda_env/asd_conda/lib/python2.7/site-packages/numpy/core/include -I/Users/mahdi/Research/Harvard/conda_env/asd_conda/include/python2.7 -c gslrandom/gslrandom.cpp -o build/temp.macosx-10.7-x86_64-2.7/gslrandom/gslrandom.o -O3 -w -std=c++0x -fopenmp
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
/usr/local/Cellar/gcc/7.1.0/bin/gcc-7 -fno-strict-aliasing -I/Users/mahdi/Research/Harvard/conda_env/asd_conda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -Igslrandom/ -I/Users/mahdi/Research/Harvard/conda_env/asd_conda/lib/python2.7/site-packages/numpy/core/include -I/Users/mahdi/Research/Harvard/conda_env/asd_conda/include/python2.7 -c gslrandom/cgslrandom.cpp -o build/temp.macosx-10.7-x86_64-2.7/gslrandom/cgslrandom.o -O3 -w -std=c++0x -fopenmp
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
/usr/local/Cellar/gcc/7.1.0/bin/g++-7 -bundle -undefined dynamic_lookup -L/Users/mahdi/Research/Harvard/conda_env/asd_conda/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-2.7/gslrandom/gslrandom.o build/temp.macosx-10.7-x86_64-2.7/gslrandom/cgslrandom.o -L/usr/local/lib -L/Users/mahdi/Research/Harvard/conda_env/asd_conda/lib -lstdc++ -lgsl -lgslcblas -o /Users/mahdi/Downloads/gslrandom-master/gslrandom/gslrandom.so -fopenmp


$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import gslrandom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gslrandom/__init__.py", line 2, in <module>
    from gslrandom.gslrandom import *
ImportError: dlopen(gslrandom/gslrandom.so, 2): Symbol not found: __ZTINSt8ios_base7failureB5cxx11E
  Referenced from: gslrandom/gslrandom.so
  Expected in: flat namespace
 in gslrandom/gslrandom.so

**Comment by slinderman** [comment]
Hi MP,
These issues are frustrating... thanks for bearing with me.  This looks like some name mangling... it's looking for a symbol in cxx11, which I think arises from including stdc++.  I just checked in some minor changes to remove the stdc++ stuff (https://github.com/slinderman/gslrandom/commit/c3e6a69556ccfe47bd2d59929ef3da7e1c4e2147). Can you pull the latest master, clean your project (i.e. remove `build` and `gslrandom/*.so`), and see if this works?  Also, just to make sure, you have installed `gsl` with homebrew, right?

**Comment by slinderman** [comment]
For what it's worth,  I was not able to reproduce on my end using `gcc-7` and `g++-7` on OSX 10.11.6.

**Comment by pakdaman** [comment]
Hi Scott,

Thank you very much for your suggestions. I just followed the steps that you mentioned. However, unfortunately, it is giving me another error when I import glsrandom in python.
These are the steps that I took:
1) I created a new conda environments called tmp_conda2
2) I installed the gsl using brew install gsl
3) I installed cython using: conda install cython
4) I cleaned the build directory by removing build/ and gslrandom/*.so
5) I rebuild the package and get the following response:
(/Users/mahdi/Research/Harvard/conda_env/tmp_conda2) Mahdis-MacBook-Pro:gslrandom mahdi$ python setup.py build_ext --inplace
/Users/mahdi/anaconda2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build_ext
building 'gslrandom.gslrandom' extension
creating build
creating build/temp.macosx-10.7-x86_64-2.7
creating build/temp.macosx-10.7-x86_64-2.7/gslrandom
/usr/local/Cellar/gcc/7.1.0/bin/gcc-7 -fno-strict-aliasing -I/Users/mahdi/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -Igslrandom/ -I/Users/mahdi/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/Users/mahdi/anaconda2/include/python2.7 -c gslrandom/gslrandom.cpp -o build/temp.macosx-10.7-x86_64-2.7/gslrandom/gslrandom.o -O3 -w -fopenmp
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
/usr/local/Cellar/gcc/7.1.0/bin/gcc-7 -fno-strict-aliasing -I/Users/mahdi/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -Igslrandom/ -I/Users/mahdi/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/Users/mahdi/anaconda2/include/python2.7 -c gslrandom/cgslrandom.cpp -o build/temp.macosx-10.7-x86_64-2.7/gslrandom/cgslrandom.o -O3 -w -fopenmp
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
/usr/local/Cellar/gcc/7.1.0/bin/g++-7 -bundle -undefined dynamic_lookup -L/Users/mahdi/anaconda2/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-2.7/gslrandom/gslrandom.o build/temp.macosx-10.7-x86_64-2.7/gslrandom/cgslrandom.o -L/usr/local/lib -L/Users/mahdi/anaconda2/lib -lgsl -lgslcblas -o /Users/mahdi/Research/Harvard/gslrandom/gslrandom/gslrandom.so -fopenmp

6) I run setup.py install and get the following messages:
(/Users/mahdi/Research/Harvard/conda_env/tmp_conda2) Mahdis-MacBook-Pro:gslrandom mahdi$ python setup.py install
/Users/mahdi/anaconda2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
creating build/lib.macosx-10.7-x86_64-2.7
creating build/lib.macosx-10.7-x86_64-2.7/gslrandom
copying gslrandom/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/gslrandom
running build_ext
building 'gslrandom.gslrandom' extension
/usr/local/Cellar/gcc/7.1.0/bin/gcc-7 -fno-strict-aliasing -I/Users/mahdi/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -Igslrandom/ -I/Users/mahdi/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/Users/mahdi/anaconda2/include/python2.7 -c gslrandom/gslrandom.cpp -o build/temp.macosx-10.7-x86_64-2.7/gslrandom/gslrandom.o -O3 -w -fopenmp
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
/usr/local/Cellar/gcc/7.1.0/bin/gcc-7 -fno-strict-aliasing -I/Users/mahdi/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -Igslrandom/ -I/Users/mahdi/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/Users/mahdi/anaconda2/include/python2.7 -c gslrandom/cgslrandom.cpp -o build/temp.macosx-10.7-x86_64-2.7/gslrandom/cgslrandom.o -O3 -w -fopenmp
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
/usr/local/Cellar/gcc/7.1.0/bin/g++-7 -bundle -undefined dynamic_lookup -L/Users/mahdi/anaconda2/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-2.7/gslrandom/gslrandom.o build/temp.macosx-10.7-x86_64-2.7/gslrandom/cgslrandom.o -L/usr/local/lib -L/Users/mahdi/anaconda2/lib -lgsl -lgslcblas -o build/lib.macosx-10.7-x86_64-2.7/gslrandom/gslrandom.so -fopenmp
running install_lib
copying build/lib.macosx-10.7-x86_64-2.7/gslrandom/gslrandom.so -> /Users/mahdi/anaconda2/lib/python2.7/site-packages/gslrandom
running install_egg_info
Removing /Users/mahdi/anaconda2/lib/python2.7/site-packages/gslrandom-0.1.4-py2.7.egg-info
Writing /Users/mahdi/anaconda2/lib/python2.7/site-packages/gslrandom-0.1.4-py2.7.egg-info


7) I installed the package using "pip install -e ." and I get the below response:
(/Users/mahdi/Research/Harvard/conda_env/tmp_conda2) Mahdis-MacBook-Pro:gslrandom mahdi$ pip install -e .
Obtaining file:///Users/mahdi/Research/Harvard/gslrandom
Requirement already satisfied: Cython>=0.20.1 in /Users/mahdi/Research/Harvard/conda_env/tmp_conda2/lib/python2.7/site-packages (from gslrandom==0.1.4)
Requirement already satisfied: numpy in /Users/mahdi/Research/Harvard/conda_env/tmp_conda2/lib/python2.7/site-packages (from gslrandom==0.1.4)
Installing collected packages: gslrandom
  Running setup.py develop for gslrandom
Successfully installed gslrandom

8) Now, I get the below error in importing gslrandom in python:
(/Users/mahdi/Research/Harvard/conda_env/tmp_conda2) Mahdis-MacBook-Pro:gslrandom mahdi$ python
Python 2.7.13 |Anaconda 4.4.0 (x86_64)| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import gslrandom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gslrandom/__init__.py", line 2, in <module>
    from gslrandom.gslrandom import *
ImportError: dlopen(gslrandom/gslrandom.so, 2): Symbol not found: ___emutls_get_address
  Referenced from: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
  Expected in: /usr/local/lib/libgcc_s.1.dylib
 in /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib

I would appreciate it very much if you have any suggestion on the error?

**Comment by pakdaman** [comment]
I should mention that I am using OSX 10.12.4 

In order to use gcc-7 and g++-7, I first installed gcc using homebrew, then I set CC, and CXX environmental variables to point to gcc-7, and g++-7, respectively. I also linked my local gcc and g++ to the new version of gcc-7 and g++-7:
ln -sf /usr/local/Cellar/gcc/7.1.0/bin/gcc-7 /usr/local/bin/gcc
ln -sf /usr/local/Cellar/gcc/7.1.0/bin/g++-7 /usr/local/bin/g++

then I installed conda and created a new conda enviroment to make sure I have used a consistent gcc from the very first step.

Thanks,
Mahdi

**Comment by slinderman** [comment]
Hi Mahdi,
Perhaps it's progress that it's failing to load a different symbol now?  Though it's obviously still frustrating!  Stackoverflow has a related post: https://stackoverflow.com/questions/13414786/missing-emutls-get-address-with-gcc-4-7-and-openmp

It suggests running `otool -L gslrandom.xxx.so` to see what shared libraries are linked to it.  In my case I see:
```
otool -L gslrandom/gslrandom.cpython-35m-darwin.so
gslrandom/gslrandom.cpython-35m-darwin.so:
        /usr/local/opt/gsl/lib/libgsl.19.dylib (compatibility version 23.0.0, current version 23.0.0)
        /usr/local/opt/gsl/lib/libgslcblas.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/local/opt/gcc/lib/gcc/7/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.23.0)
        /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
        /usr/local/lib/gcc/7/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

Do you see anything strange in your output? e.g. links against older libs from older versions of gcc?  different versions?

**Comment by pakdaman** [comment]
Hi Scott,
Thank you very much for your response. gslrandom.so is the only .so file I can see in in the gslrandom folder! I ran the otool command and it gave me the following results:
(/Users/mahdi/Research/Harvard/conda_env/tmp2_conda2) Mahdis-MacBook-Pro:gslrandom mahdi$ otool -L gslrandom/gslrandom.so 
gslrandom/gslrandom.so:
	/usr/local/opt/gsl/lib/libgsl.23.dylib (compatibility version 24.0.0, current version 24.0.0)
	/usr/local/opt/gsl/lib/libgslcblas.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/gcc/lib/gcc/7/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.23.0)
	/usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
	/usr/local/lib/gcc/7/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)

The results similar to yours, except for "/usr/local/opt/gsl/lib/libgsl.23.dylib" and "/usr/lib/libSystem.B.dylib". I am wondering if you have any suggestion?

By the way, just to make sure I am using similar setup as you, are you also using gcc7 ?

**Comment by slinderman** [comment]
I'm not sure what's going on.  I don't think the versions of gsl or libSystem.B.dylib should matter (though I could be wrong).  One thing that seems curious is that it's looking for the missing symbol in `/usr/local/lib/libgcc_s.1.dylib` but the output of `otool -L` has `/usr/local/lib/gcc/7/libgcc_s.1.dylib`.  

I'm back on stackoverflow -- this post goes through the same steps as we have, but it includes a bit of C++ that you could try test compiling.  https://stackoverflow.com/questions/43594977/osx-10-12-gcc-openmp-error/43643883

To reiterate, the things that seem to have worked in the past are:
```
brew rm gcc
brew install gcc --without-multilib
```
and if that doesn't do it, also try uninstalling Xcode and  reinstalling with
```
xcode-select --install
```

**Comment by pakdaman** [comment]
Hi Scott,
Thank you very much for your recommendations. I finally installed and imported gslrandom successfully. Here, I summarize all the steps that lead to the successful installation of the package on my mac:

brew install gcc --without-multilib
brew install gsl

export CXX=/usr/local/Cellar/gcc/7.1.0/bin/g++-7
export CC=/usr/local/Cellar/gcc/7.1.0/bin/gcc-7
export DYLD_LIBRARY_PATH=/usr/local/Cellar/gcc/7.1.0/lib/gcc/7/:$DYLD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/Cellar/gcc/7.1.0/lib/gcc/7/:$LD_LIBRARY_PATH
#in the above 4 commands you should use your the path related to the installed gcc on your own computer

#cd to gslrandom directory
rm -rf build
rm gslrandom/*.so
python setup.py build_ext --inplace
python setup.py install
pip install -e .

Thank you again for your help and support.

**Comment by slinderman** [comment]
Woo! Glad you got it working!  I don't know why DYLD_LIBRARY_PATH and
LD_LIBRARY_PATH needed to be set (they're not on my computer) but that
would explain the failure to find the symbol.

Regarding the installation:  remember that `python setup.py build_ext
--inplace` just compiles and builds to output the .so file.  `python
setup.py install` is a manual way to install packages from source; it will
compile and build under the hood, then copy the result to site-packages.
That way you can import the package even when your python shell is working
in another directory. `pip install -e .` will do all that `python setup.py
install` does and more. Specifically, it can download dependencies and
store metadata to make it easy to uninstall and upgrade packages.  The `-e
.` option installs in developer mode, which means that rather than copying
to site-packages, it will make symlinks to the current directory in
site-packages. That way if you change the code it will automatically be
reflected next time you import (unless you change the cython in which case
you also need to recompile).  Does that all make sense?

**Comment by pakdaman** [comment]
Scott,

Thank you very much for your clear and detailed descriptions.

Best,
Mahdi
